replicaCount: 1
image:
  repository: docker.io/zelarsoftdev/docker_web_app
  pullPolicy: IfNotPresent
  tag: 1.0.0

service:
  type: ClusterIP
  port: 6566

resources: {}

nodeSelector: {}

tolerations: []
affinity: {}