name: CI/CD Pipeline

on:
  push:
    branches:
      - demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Build Docker image
        run: |
          docker build --arch=x86_64 -t zelarsoftdev/welcome-app:1.0.0 .
      
      - name: Push Docker image
        run: |
          docker push zelarsoftdev/welcome-app:1.0.0
          
      - name: Deploy with Helm
        run: |
          helm upgrade --install welcome-app helm/welcome-app --namespace default
