name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t docker_web_app:1.0.0 .

    - name: Push Docker Image
      run: |
        docker push docker_web_app:1.0.0

    - name: Deploy
      run: |
        helm upgrade --install docker-web-app ./helm