name: Docker Build and Deploy

on:
  push:
    branches:
      - demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Set up QEMU (Optional, if needed for multi-architecture)
      uses: docker/setup-qemu-action@v1

    - name: Build Docker image
      run: |
        docker build --arch=x86_64 -t zelarsoftdev/welcome:main .

    - name: Push Docker image
      run: |
        docker push zelarsoftdev/welcome:main
